django_api:
  restart: always
  build: ./django_api
  expose:
    - "8000"
  links:
    - postgres:postgres
    - redis:redis
  volumes:
    - ./django_api:/code
  env_file: .env
  environment:
    DEBUG: 'true'
  command: python manage.py runserver 0.0.0.0:8000

# frontend:
#   restart: always
#   build: ./frontend
#   expose:
#     - "3000"
#   volumes:
#     - ./frontend:/code
#   environment:
#     NODE_ENV: 'development'
#   command: yarn run start

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "80:80"
  volumes:
    - ./django_api/static:/www/static
  links:
    - django_api:django_api
    # - frontend:frontend
  extra_hosts:
    # requires `export DOCKERHOST="$(ifconfig en0 inet | grep "inet " | awk -F'[: ]+' '{ print $2 }')"` in ~/.bash_profile
    - "frontend:$DOCKERHOST"


postgres:
  restart: always
  image: postgres:latest
  ports:
    - "5432:5432"
  volumes:
    - pgdata:/var/lib/postgresql/data/

redis:
  restart: always
  image: redis:latest
  ports:
    - "6379:6379"
  volumes:
    - redisdata:/data
